/**
 * Use these variables when you tailor your ArkTS code. They must be of the const type.
 */
export const HAR_VERSION = '0.11.0-0.0.1';
export const BUILD_MODE_NAME = 'debug';
export const DEBUG = true;
export const TARGET_NAME = 'default';
export const APP_NAME = 'Keys Example';
export const BUNDLE_ID = 'com.example.rnkeys.dev';
export const ANDROID_CODE = '50';
export const PACKAGE_ID = 'com.example.rnkeys.dev';

/**
 * BuildProfile Class is used only for compatibility purposes.
 */
export default class BuildProfile { 
	static readonly HAR_VERSION = HAR_VERSION;
	static readonly BUILD_MODE_NAME = BUILD_MODE_NAME;
	static readonly DEBUG = DEBUG;
	static readonly TARGET_NAME = TARGET_NAME;
	static readonly APP_NAME = APP_NAME;
	static readonly BUNDLE_ID = BUNDLE_ID;
	static readonly ANDROID_CODE = ANDROID_CODE;
	static readonly PACKAGE_ID = PACKAGE_ID;
}